/* =========================================================
   ΜΕΡΟΣ 2: EXTRA ΕΠΕΚΤΑΣΗ
   ========================================================= */

CREATE TABLE ASTHENIS (
    AMKA            VARCHAR2(20) NOT NULL,
    ONOMA           VARCHAR2(100) NOT NULL,
    EPWNYMO         VARCHAR2(100) NOT NULL,
    FYLO            VARCHAR2(1),
    HM_GENNISIS     DATE,
    DIEYTHINSI      VARCHAR2(200),
    POLI            VARCHAR2(100),
    TILEFONO        VARCHAR2(20),
    EMAIL           VARCHAR2(200)
) LOGGING;

ALTER TABLE ASTHENIS
    ADD CONSTRAINT ASTHENIS_PK PRIMARY KEY (AMKA);

ALTER TABLE ASTHENIS
    ADD CONSTRAINT ASTHENIS_FYLO_CHK CHECK (FYLO IN ('A','G'));

ALTER TABLE ASTHENIS
    ADD CONSTRAINT ASTHENIS_EMAIL_UK UNIQUE (EMAIL);


CREATE TABLE RANDEVOU (
    RANDEVOU_ID     NUMBER NOT NULL,
    AMKA_ASTHENI    VARCHAR2(20) NOT NULL,
    AT_IATROU       VARCHAR2(20) NOT NULL,
    IMEROMINIA      DATE NOT NULL,
    WRA             VARCHAR2(5) NOT NULL,
    AITIA           VARCHAR2(300),
    KATASTASI       VARCHAR2(20) DEFAULT 'PROGRAMMED'
) LOGGING;

ALTER TABLE RANDEVOU
    ADD CONSTRAINT RANDEVOU_PK PRIMARY KEY (RANDEVOU_ID);

ALTER TABLE RANDEVOU
    ADD CONSTRAINT RANDEVOU_KATASTASI_CHK
    CHECK (KATASTASI IN ('PROGRAMMED', 'COMPLETED', 'CANCELLED'));

ALTER TABLE RANDEVOU
    ADD CONSTRAINT RANDEVOU_UNQ
    UNIQUE (AMKA_ASTHENI, AT_IATROU, IMEROMINIA, WRA);


CREATE TABLE EXETASI (
    EXETASI_ID          NUMBER NOT NULL,
    PERIGRAFI           VARCHAR2(200) NOT NULL,
    KOSTOS              NUMBER(10,2),
    ONOMA_ERGASTIRIOU   VARCHAR2(100) NOT NULL
) LOGGING;

ALTER TABLE EXETASI
    ADD CONSTRAINT EXETASI_PK PRIMARY KEY (EXETASI_ID);

ALTER TABLE EXETASI
    ADD CONSTRAINT EXETASI_KOSTOS_CHK CHECK (KOSTOS >= 0);


CREATE TABLE APOTELESMA_EXETASIS (
    APOTELESMA_ID       NUMBER NOT NULL,
    AMKA_ASTHENI        VARCHAR2(20) NOT NULL,
    EXETASI_ID          NUMBER NOT NULL,
    AT_IATROU           VARCHAR2(20),
    HMEROMINIA_EXETASIS DATE NOT NULL,
    APOTELESMA          VARCHAR2(1000),
    SXOLIA              VARCHAR2(1000)
) LOGGING;

ALTER TABLE APOTELESMA_EXETASIS
    ADD CONSTRAINT APOT_EXETASIS_PK PRIMARY KEY (APOTELESMA_ID);


CREATE TABLE XRISTIS_LOGARIASMOS (
    USERNAME            VARCHAR2(50) NOT NULL,
    PASSWORD_HASH       VARCHAR2(200) NOT NULL,
    ROLOS               VARCHAR2(30) NOT NULL,
    AT_IATROU           VARCHAR2(20),
    AT_NOSILEYTI        VARCHAR2(20),
    AT_PARAIATRIKOU     VARCHAR2(20),
    IS_ACTIVE           NUMBER(1) DEFAULT 1
) LOGGING;

ALTER TABLE XRISTIS_LOGARIASMOS
    ADD CONSTRAINT XRISTIS_LOG_PK PRIMARY KEY (USERNAME);

ALTER TABLE XRISTIS_LOGARIASMOS
    ADD CONSTRAINT XRISTIS_LOG_ROLOS_CHK
    CHECK (ROLOS IN ('ADMIN', 'DOCTOR', 'NURSE', 'LAB'));

ALTER TABLE XRISTIS_LOGARIASMOS
    ADD CONSTRAINT XRISTIS_LOG_ACTIVE_CHK
    CHECK (IS_ACTIVE IN (0,1));

ALTER TABLE XRISTIS_LOGARIASMOS
    ADD CONSTRAINT XRISTIS_ONE_PERSON_CHK
    CHECK (
        (CASE WHEN AT_IATROU IS NOT NULL THEN 1 ELSE 0 END) +
        (CASE WHEN AT_NOSILEYTI IS NOT NULL THEN 1 ELSE 0 END) +
        (CASE WHEN AT_PARAIATRIKOU IS NOT NULL THEN 1 ELSE 0 END)
        <= 1
    );


/* =========================================================
   ΞΕΝΑ ΚΛΕΙΔΙΑ EXTRA ΠΙΝΑΚΩΝ
   ========================================================= */

ALTER TABLE RANDEVOU
    ADD CONSTRAINT RANDEVOU_ASTHENIS_FK
    FOREIGN KEY (AMKA_ASTHENI)
    REFERENCES ASTHENIS (AMKA)
    NOT DEFERRABLE;

ALTER TABLE RANDEVOU
    ADD CONSTRAINT RANDEVOU_IATROS_FK
    FOREIGN KEY (AT_IATROU)
    REFERENCES IATROS (AT)
    NOT DEFERRABLE;


ALTER TABLE EXETASI
    ADD CONSTRAINT EXETASI_ERG_FK
    FOREIGN KEY (ONOMA_ERGASTIRIOU)
    REFERENCES ERGASTIRIO (ONOMA)
    NOT DEFERRABLE;


ALTER TABLE APOTELESMA_EXETASIS
    ADD CONSTRAINT APOT_EXET_AS_FK
    FOREIGN KEY (AMKA_ASTHENI)
    REFERENCES ASTHENIS (AMKA)
    NOT DEFERRABLE;

ALTER TABLE APOTELESMA_EXETASIS
    ADD CONSTRAINT APOT_EXET_EX_FK
    FOREIGN KEY (EXETASI_ID)
    REFERENCES EXETASI (EXETASI_ID)
    NOT DEFERRABLE;

ALTER TABLE APOTELESMA_EXETASIS
    ADD CONSTRAINT APOT_EXET_IATROS_FK
    FOREIGN KEY (AT_IATROU)
    REFERENCES IATROS (AT)
    NOT DEFERRABLE;


ALTER TABLE XRISTIS_LOGARIASMOS
    ADD CONSTRAINT XRISTIS_LOG_IATROS_FK
    FOREIGN KEY (AT_IATROU)
    REFERENCES IATROS (AT)
    NOT DEFERRABLE;

ALTER TABLE XRISTIS_LOGARIASMOS
    ADD CONSTRAINT XRISTIS_LOG_NOS_FK
    FOREIGN KEY (AT_NOSILEYTI)
    REFERENCES NOSILEYTIS (AT)
    NOT DEFERRABLE;

ALTER TABLE XRISTIS_LOGARIASMOS
    ADD CONSTRAINT XRISTIS_LOG_PARA_FK
    FOREIGN KEY (AT_PARAIATRIKOU)
    REFERENCES PARAIATRIKO_PROSOPIKO (AT)
    NOT DEFERRABLE;