/* =========================================================
   ΜΕΡΟΣ 3: VIEWS
   ========================================================= */

CREATE OR REPLACE VIEW VW_GIATROS_RANDEVOU AS
SELECT
    R.RANDEVOU_ID,
    R.AT_IATROU,
    A.AMKA,
    A.ONOMA AS ONOMA_ASTHENI,
    A.EPWNYMO AS EPWNYMO_ASTHENI,
    R.IMEROMINIA,
    R.WRA,
    R.AITIA,
    R.KATASTASI
FROM RANDEVOU R
JOIN ASTHENIS A ON A.AMKA = R.AMKA_ASTHENI;

CREATE OR REPLACE VIEW VW_ERGASTIRIO_EXETASEIS AS
SELECT
    E.EXETASI_ID,
    E.PERIGRAFI,
    E.KOSTOS,
    E.ONOMA_ERGASTIRIOU,
    APE.APOTELESMA_ID,
    APE.AMKA_ASTHENI,
    APE.HMEROMINIA_EXETASIS,
    APE.APOTELESMA
FROM EXETASI E
LEFT JOIN APOTELESMA_EXETASIS APE
    ON E.EXETASI_ID = APE.EXETASI_ID;


/* =========================================================
   ROLES
   ========================================================= */

CREATE ROLE ROLE_ADMIN_NOSOKOMEIOU;
CREATE ROLE ROLE_GIATROS;
CREATE ROLE ROLE_NOSILEYTIS;
CREATE ROLE ROLE_ERGASTIRIO;


/* =========================================================
   PRIVILEGES ΣΕ ΡΟΛΟΥΣ
   ========================================================= */

-- ADMIN
GRANT SELECT, INSERT, UPDATE, DELETE ON ERGASTIRIO TO ROLE_ADMIN_NOSOKOMEIOU;
GRANT SELECT, INSERT, UPDATE, DELETE ON KLINIKI TO ROLE_ADMIN_NOSOKOMEIOU;
GRANT SELECT, INSERT, UPDATE, DELETE ON IATROS TO ROLE_ADMIN_NOSOKOMEIOU;
GRANT SELECT, INSERT, UPDATE, DELETE ON NOSILEYTIS TO ROLE_ADMIN_NOSOKOMEIOU;
GRANT SELECT, INSERT, UPDATE, DELETE ON PARAIATRIKO_PROSOPIKO TO ROLE_ADMIN_NOSOKOMEIOU;
GRANT SELECT, INSERT, UPDATE, DELETE ON ERGAZETAI TO ROLE_ADMIN_NOSOKOMEIOU;
GRANT SELECT, INSERT, UPDATE, DELETE ON TILEFONO_ERGASTIRIOU TO ROLE_ADMIN_NOSOKOMEIOU;
GRANT SELECT, INSERT, UPDATE, DELETE ON ASTHENIS TO ROLE_ADMIN_NOSOKOMEIOU;
GRANT SELECT, INSERT, UPDATE, DELETE ON RANDEVOU TO ROLE_ADMIN_NOSOKOMEIOU;
GRANT SELECT, INSERT, UPDATE, DELETE ON EXETASI TO ROLE_ADMIN_NOSOKOMEIOU;
GRANT SELECT, INSERT, UPDATE, DELETE ON APOTELESMA_EXETASIS TO ROLE_ADMIN_NOSOKOMEIOU;
GRANT SELECT, INSERT, UPDATE, DELETE ON XRISTIS_LOGARIASMOS TO ROLE_ADMIN_NOSOKOMEIOU;

GRANT SELECT ON VW_GIATROS_RANDEVOU TO ROLE_ADMIN_NOSOKOMEIOU;
GRANT SELECT ON VW_ERGASTIRIO_EXETASEIS TO ROLE_ADMIN_NOSOKOMEIOU;


-- ΓΙΑΤΡΟΣ
GRANT SELECT ON KLINIKI TO ROLE_GIATROS;
GRANT SELECT ON ERGASTIRIO TO ROLE_GIATROS;
GRANT SELECT ON ASTHENIS TO ROLE_GIATROS;
GRANT SELECT, INSERT, UPDATE ON RANDEVOU TO ROLE_GIATROS;
GRANT SELECT ON EXETASI TO ROLE_GIATROS;
GRANT SELECT, INSERT ON APOTELESMA_EXETASIS TO ROLE_GIATROS;
GRANT SELECT ON VW_GIATROS_RANDEVOU TO ROLE_GIATROS;


-- ΝΟΣΗΛΕΥΤΗΣ
GRANT SELECT ON KLINIKI TO ROLE_NOSILEYTIS;
GRANT SELECT ON ASTHENIS TO ROLE_NOSILEYTIS;
GRANT SELECT ON RANDEVOU TO ROLE_NOSILEYTIS;
GRANT UPDATE ON ASTHENIS TO ROLE_NOSILEYTIS;


-- ΕΡΓΑΣΤΗΡΙΟ / ΠΑΡΑΪΑΤΡΙΚΟ
GRANT SELECT ON ERGASTIRIO TO ROLE_ERGASTIRIO;
GRANT SELECT ON EXETASI TO ROLE_ERGASTIRIO;
GRANT SELECT ON ASTHENIS TO ROLE_ERGASTIRIO;
GRANT SELECT, INSERT, UPDATE ON APOTELESMA_EXETASIS TO ROLE_ERGASTIRIO;
GRANT SELECT ON VW_ERGASTIRIO_EXETASEIS TO ROLE_ERGASTIRIO;


/* =========================================================
   USERS
   ========================================================= */

CREATE USER ADMIN_HOSP IDENTIFIED BY Admin123!;
CREATE USER GIATROS1 IDENTIFIED BY Doctor123!;
CREATE USER NOSILEYTIS1 IDENTIFIED BY Nurse123!;
CREATE USER LAB_USER1 IDENTIFIED BY Lab123!;


/* =========================================================
   SYSTEM PRIVILEGES
   ========================================================= */

GRANT CREATE SESSION TO ADMIN_HOSP;
GRANT CREATE SESSION TO GIATROS1;
GRANT CREATE SESSION TO NOSILEYTIS1;
GRANT CREATE SESSION TO LAB_USER1;


/* =========================================================
   ROLE ASSIGNMENTS
   ========================================================= */

GRANT ROLE_ADMIN_NOSOKOMEIOU TO ADMIN_HOSP;
GRANT ROLE_GIATROS TO GIATROS1;
GRANT ROLE_NOSILEYTIS TO NOSILEYTIS1;
GRANT ROLE_ERGASTIRIO TO LAB_USER1;