/* =========================================================
   ΜΕΡΟΣ 1: ΑΡΧΙΚΟ ΣΧΗΜΑ
   ========================================================= */

CREATE TABLE ERGASTIRIO (
    ONOMA           VARCHAR2(100) NOT NULL,
    DIEYTHYNTIS     VARCHAR2(100)
) LOGGING;

ALTER TABLE ERGASTIRIO
    ADD CONSTRAINT ERGASTIRIO_PK PRIMARY KEY (ONOMA);


CREATE TABLE KLINIKI (
    ONOMA               VARCHAR2(100) NOT NULL,
    DIEYTHYNTIS         VARCHAR2(100),
    ARITHMOS_KLINWN     NUMBER,
    ARITHMOS_ASTHENWN   NUMBER
) LOGGING;

ALTER TABLE KLINIKI
    ADD CONSTRAINT KLINIKI_PK PRIMARY KEY (ONOMA);

ALTER TABLE KLINIKI
    ADD CONSTRAINT KLINIKI_KLINES_CHK CHECK (ARITHMOS_KLINWN >= 0);

ALTER TABLE KLINIKI
    ADD CONSTRAINT KLINIKI_ASTHENEIS_CHK CHECK (ARITHMOS_ASTHENWN >= 0);


CREATE TABLE NOSILEYTIS (
    AT              VARCHAR2(20) NOT NULL,
    ONOMA           VARCHAR2(100),
    EPWNYMO         VARCHAR2(100),
    EMAIL           VARCHAR2(200),
    TILEFONO        VARCHAR2(20),
    POLI            VARCHAR2(100),
    DIEYTHINSI      VARCHAR2(200),
    EIDIKOTITA      VARCHAR2(100)
) LOGGING;

ALTER TABLE NOSILEYTIS
    ADD CONSTRAINT NOSILEYTIS_PK PRIMARY KEY (AT);

ALTER TABLE NOSILEYTIS
    ADD CONSTRAINT NOSILEYTIS_EMAIL_UK UNIQUE (EMAIL);


CREATE TABLE IATROS (
    AT                  VARCHAR2(20) NOT NULL,
    AM                  VARCHAR2(20),
    EPWNYMO             VARCHAR2(100),
    ONOMA               VARCHAR2(100),
    EIDIKOTITA          VARCHAR2(100),
    DIEYTHINSI          VARCHAR2(200),
    POLI                VARCHAR2(100),
    TILEFONO            VARCHAR2(20),
    EMAIL               VARCHAR2(200),
    ONOMA_ERGASTIRIOU   VARCHAR2(100),
    ONOMA_KLINIKIS      VARCHAR2(100)
) LOGGING;

ALTER TABLE IATROS
    ADD CONSTRAINT IATROS_PK PRIMARY KEY (AT);

ALTER TABLE IATROS
    ADD CONSTRAINT IATROS_AM_UK UNIQUE (AM);

ALTER TABLE IATROS
    ADD CONSTRAINT IATROS_EMAIL_UK UNIQUE (EMAIL);


CREATE TABLE PARAIATRIKO_PROSOPIKO (
    AT                  VARCHAR2(20) NOT NULL,
    AFM                 VARCHAR2(20),
    ONOMA               VARCHAR2(100),
    EPWNYMO             VARCHAR2(100),
    EIDIKOTITA          VARCHAR2(100),
    ONOMA_ERGASTIRIOU   VARCHAR2(100)
) LOGGING;

ALTER TABLE PARAIATRIKO_PROSOPIKO
    ADD CONSTRAINT PARAIATRIKO_PROSOPIKO_PK PRIMARY KEY (AT);

ALTER TABLE PARAIATRIKO_PROSOPIKO
    ADD CONSTRAINT PARAIATRIKO_AFM_UK UNIQUE (AFM);


CREATE TABLE ERGAZETAI (
    ONOMA_KLINIKIS  VARCHAR2(100) NOT NULL,
    AT_NOSILEYTI    VARCHAR2(20) NOT NULL
) LOGGING;

ALTER TABLE ERGAZETAI
    ADD CONSTRAINT ERGAZETAI_PK PRIMARY KEY (ONOMA_KLINIKIS, AT_NOSILEYTI);


CREATE TABLE TILEFONO_ERGASTIRIOU (
    TILEFONO            VARCHAR2(20) NOT NULL,
    ONOMA_ERGASTIRIOU   VARCHAR2(100) NOT NULL
) LOGGING;

ALTER TABLE TILEFONO_ERGASTIRIOU
    ADD CONSTRAINT TILEFONO_ERG_PK PRIMARY KEY (TILEFONO, ONOMA_ERGASTIRIOU);


/* =========================================================
   ΞΕΝΑ ΚΛΕΙΔΙΑ ΑΡΧΙΚΟΥ ΣΧΗΜΑΤΟΣ
   ========================================================= */

ALTER TABLE ERGAZETAI
    ADD CONSTRAINT ERGAZETAI_KLINIKI_FK
    FOREIGN KEY (ONOMA_KLINIKIS)
    REFERENCES KLINIKI (ONOMA)
    NOT DEFERRABLE;

ALTER TABLE ERGAZETAI
    ADD CONSTRAINT ERGAZETAI_NOSILEYTIS_FK
    FOREIGN KEY (AT_NOSILEYTI)
    REFERENCES NOSILEYTIS (AT)
    NOT DEFERRABLE;

ALTER TABLE IATROS
    ADD CONSTRAINT IATROS_ERG_FK
    FOREIGN KEY (ONOMA_ERGASTIRIOU)
    REFERENCES ERGASTIRIO (ONOMA)
    NOT DEFERRABLE;

ALTER TABLE IATROS
    ADD CONSTRAINT IATROS_KLINIKI_FK
    FOREIGN KEY (ONOMA_KLINIKIS)
    REFERENCES KLINIKI (ONOMA)
    NOT DEFERRABLE;

ALTER TABLE PARAIATRIKO_PROSOPIKO
    ADD CONSTRAINT PARA_ERG_FK
    FOREIGN KEY (ONOMA_ERGASTIRIOU)
    REFERENCES ERGASTIRIO (ONOMA)
    NOT DEFERRABLE;

ALTER TABLE TILEFONO_ERGASTIRIOU
    ADD CONSTRAINT TILEFONO_ERG_ERG_FK
    FOREIGN KEY (ONOMA_ERGASTIRIOU)
    REFERENCES ERGASTIRIO (ONOMA)
    NOT DEFERRABLE;