-- ============================================
-- ΒΑΣΗ HOSPITAL – 22 ΑΣΚΗΣΕΙΣ SQL
-- ============================================

-- Άσκηση 1: Εισαγωγή δεδομένων
INSERT INTO ERGASTIRIO (ONOMA, DIEYTHYNTIS) VALUES ('Μικροβιολογικό','Παπαδόπουλος Ιωάννης');
INSERT INTO ERGASTIRIO (ONOMA, DIEYTHYNTIS) VALUES ('Ακτινολογικό','Κωνσταντίνου Μαρία');
INSERT INTO KLINIKI (ONOMA,DIEYTHYNTIS,ARITHMOS_KLINWN,ARITHMOS_ASTHENWN)
VALUES ('Καρδιολογική','Λάμπρου Νίκος',20,35);
INSERT INTO KLINIKI (ONOMA,DIEYTHYNTIS,ARITHMOS_KLINWN,ARITHMOS_ASTHENWN)
VALUES ('Ορθοπεδική','Σταθάκη Άννα',15,22);

-- Άσκηση 2: SELECT απλό
SELECT ONOMA, DIEYTHYNTIS FROM ERGASTIRIO;

-- Άσκηση 3: SELECT με WHERE
SELECT ONOMA, ARITHMOS_KLINWN FROM KLINIKI WHERE ARITHMOS_KLINWN > 18;

-- Άσκηση 4: INNER JOIN
SELECT n.AT, n.ONOMA, n.EPWNYMO, e.ONOMA_KLINIKIS
FROM NOSILEYTIS n
INNER JOIN ERGAZETAI e ON n.AT = e.AT_NOSILEYTI;

-- Άσκηση 5: JOIN πολλών πινάκων
SELECT i.ONOMA AS DOCTOR_NAME, i.EPWNYMO, i.EIDIKOTITA,
       k.ONOMA AS KLINIKI, e.ONOMA AS ERGASTIRIO
FROM IATROS i
JOIN KLINIKI k ON i.ONOMA_KLINIKIS = k.ONOMA
JOIN ERGASTIRIO e ON i.ONOMA_ERGASTIRIOU = e.ONOMA;

-- Άσκηση 6: LEFT OUTER JOIN
SELECT k.ONOMA AS KLINIKI, i.ONOMA AS DOCTOR_NAME
FROM KLINIKI k
LEFT OUTER JOIN IATROS i ON k.ONOMA = i.ONOMA_KLINIKIS;

-- Άσκηση 7: RIGHT OUTER JOIN
SELECT e.ONOMA AS ERGASTIRIO, i.ONOMA AS DOCTOR_NAME
FROM IATROS i
RIGHT OUTER JOIN ERGASTIRIO e ON i.ONOMA_ERGASTIRIOU = e.ONOMA;

-- Άσκηση 8: FULL OUTER JOIN
SELECT e.ONOMA AS ERGASTIRIO, i.ONOMA AS DOCTOR_NAME
FROM IATROS i
FULL OUTER JOIN ERGASTIRIO e ON i.ONOMA_ERGASTIRIOU = e.ONOMA;

-- Άσκηση 9: GROUP BY
SELECT ONOMA_KLINIKIS, COUNT(*) AS PLITHOS_NOSILEYTON
FROM ERGAZETAI
GROUP BY ONOMA_KLINIKIS;

-- Άσκηση 10: UPDATE
UPDATE KLINIKI SET ARITHMOS_KLINWN = ARITHMOS_KLINWN + 5 WHERE ONOMA='Καρδιολογική';

-- Άσκηση 11: DELETE
DELETE FROM ERGAZETAI WHERE AT_NOSILEYTI='N002';
DELETE FROM NOSILEYTIS WHERE AT='N002';

-- Άσκηση 12: VIEW 1
CREATE VIEW VIEW_DOCTORS AS
SELECT i.AT,i.ONOMA,i.EPWNYMO,i.EIDIKOTITA,
       k.ONOMA AS KLINIKI,e.ONOMA AS ERGASTIRIO
FROM IATROS i
JOIN KLINIKI k ON i.ONOMA_KLINIKIS=k.ONOMA
JOIN ERGASTIRIO e ON i.ONOMA_ERGASTIRIOU=e.ONOMA;

-- Άσκηση 13: VIEW 2
CREATE VIEW VIEW_NURSES AS
SELECT n.AT,n.ONOMA,n.EPWNYMO,e.ONOMA_KLINIKIS
FROM NOSILEYTIS n
JOIN ERGAZETAI e ON n.AT=e.AT_NOSILEYTI;

-- Άσκηση 14: VIEW 3
CREATE VIEW VIEW_KLINIKI_STATS AS
SELECT k.ONOMA,k.ARITHMOS_KLINWN,k.ARITHMOS_ASTHENWN,
       COUNT(e.AT_NOSILEYTI) AS PLITHOS_NOSILEYTON
FROM KLINIKI k
LEFT JOIN ERGAZETAI e ON k.ONOMA=e.ONOMA_KLINIKIS
GROUP BY k.ONOMA,k.ARITHMOS_KLINWN,k.ARITHMOS_ASTHENWN;

-- Άσκηση 15: ORDER BY
SELECT ONOMA,EPWNYMO,EIDIKOTITA FROM IATROS ORDER BY EPWNYMO ASC;

-- Άσκηση 16: DISTINCT
SELECT DISTINCT EIDIKOTITA FROM IATROS;

-- Άσκηση 17: LIKE
SELECT ONOMA,EPWNYMO,EMAIL FROM NOSILEYTIS WHERE EMAIL LIKE '%@hospital.gr';

-- Άσκηση 18: BETWEEN
SELECT ONOMA,ARITHMOS_KLINWN FROM KLINIKI WHERE ARITHMOS_KLINWN BETWEEN 15 AND 25;

-- Άσκηση 19: IN
SELECT ONOMA,EPWNYMO,EIDIKOTITA FROM IATROS WHERE EIDIKOTITA IN ('Καρδιολόγος','Ορθοπεδικός');

-- Άσκηση 20: HAVING
SELECT ONOMA_KLINIKIS,COUNT(*) AS PLITHOS_NOSILEYTON
FROM ERGAZETAI
GROUP BY ONOMA_KLINIKIS
HAVING COUNT(*)>1;

-- Άσκηση 21: SUBQUERY
SELECT ONOMA,EPWNYMO,EIDIKOTITA
FROM IATROS
WHERE ONOMA_KLINIKIS IN (
    SELECT ONOMA FROM KLINIKI WHERE ARITHMOS_ASTHENWN>30
);

-- Άσκηση 22: Aggregates
SELECT AVG(ARITHMOS_KLINWN) AS MESOS_KLINWN FROM KLINIKI;
